function [status, results] = AFQ_mrtrix_5ttgen(T1_file, ...
                                                  tt5_filename, ...
                                                  bkgrnd, ...
                                                  verbose, ...
                                                  mrtrixVersion,...
                                                  tool, ...
                                                  nthreads) 
%
% Convert a nifti image to a mrtrix .mif image.
% Do this: 5ttgen fsl T1.mif 5tt.mif
% To do: explore more options of the software
% Example
% AFQ_mrtrix_5ttgen('T1.mif', '5tt.mif') 

if notDefined('bkgrnd'),  bkgrnd  = false;end
if notDefined('verbose'), verbose = true; end
if notDefined('mrtrixVersion'), mrtrixVersion = 3; end

% fsl or freesurfer can be selected
cmd_str = sprintf('5ttgen %s %s %s -nthreads %i', ...
                  tool, T1_file, tt5_filename, nthreads); 

[status,results] = AFQ_mrtrix_cmd(cmd_str, ...
                                  bkgrnd, ...
                                  verbose, ...
                                  mrtrixVersion); 
