Description of AFQ_AddNewFiberGroup
Home > functions > AFQ_AddNewFiberGroup.m
AFQ_AddNewFiberGroup
PURPOSE
THIS FUNCTION IS STILL BEING DEVELOPED
SYNOPSIS
function afq = AFQ_AddNewFiberGroup(afq,fgName,roi1Name,roi2Name,cleanFibers,computeVals)
DESCRIPTION
 THIS FUNCTION IS STILL BEING DEVELOPED
 Add new fiber groups from any segmentation proceedure to an afq structure
 afq = AFQ_AddNewFiberGroup(afq, fgName, roi1Name, roi2Name, [cleanFibers = true],[computeVals = true])
 By default AFQ_run will segment the 20 fiber groups defined in the Mori
 white matter atlas and save all the relevant information in the afq
 structure. Aditional groups defined manually or with other segmentation
 algorithms can be added to the afq structure with AFQ_AddNewFiberGroup.
 By default this function will take in (1) an afq strucutre that has already
 been passed through AFQ_run (see AFQ_Create and AFQ_run), (2) the name of
 the new fiber group which should be in each subject's fibers directory,
 and (3) the name of two waypoint ROIs that the fiber group passes through
 which should be in each subjects ROIs directory. The necesary fields in
 the afq structure will be populated, TractProfiles will be calculated and
 added to the structure (See AFQ_CreateTractProfile and
 AFQ_ComputeTractProperties) and the new afq structure will be returned.
 Feel free to take an already segmented fiber group and associate it with
 2 new ROIs in order to define the edges of the profile differently.
 Inputs:
 afq        - An afq structure output from AFQ_run (see also AFQ_Create)
 fgName     - A string containing the name of the fiber group. The fiber
              group should be in each subject's fibers directory (with the
              same name). This can be either a .mat file or a .pdb file.
              If the fgName file does not exist then the fiber group will
              be defined by intersecting the subject's wholeBrainFG with
              the two ROIs.
 roi1Name   - A string containing the name of the first waypoint ROI.
              The ROI should be in each subject's ROIs directory
 roi2Name   - A string containing the name of the second ROI
 cleanFibers- Locigal defining whether the fibers should be cleaned. See
              AFQ_removeFiberOutliers
 computeVals- Logical defining whether TractProfiles should be calculated
              for the new fiber group for all of the diffusion (and other)
              parameters that are  already contained in the afq structure
 Copyright Jason D. Yeatman November 2012
CROSS-REFERENCE INFORMATION
This function calls:
AFQ_ComputeNorms Compute tract diffusion profile norms from control group data
AFQ_ComputeTractProperties Compute diffusion properties along the trajectory of the fiber groups.
AFQ_LoadROIs Load the two ROIs used to define a fiber group
AFQ_ParamaterizeTractShape Paramaterize curvature and torsion along a tract profile
AFQ_TractProfileVolume THIS FUNCTION IS STILL BEING DEVELOPED
AFQ_get Get value from afq structure
AFQ_removeFiberOutliers Remove fibers from a fiber group that differ substantially from the
AFQ_set Set properties of afq object
isafq Check if a variable is an afq structure
This function is called by:
SOURCE CODE
function afq = AFQ_AddNewFiberGroup(afq,fgName,roi1Name,roi2Name,cleanFibers,computeVals)
% THIS FUNCTION IS STILL BEING DEVELOPED
% Add new fiber groups from any segmentation proceedure to an afq structure
%
% afq = AFQ_AddNewFiberGroup(afq, fgName, roi1Name, roi2Name, [cleanFibers = true],[computeVals = true])
%
% By default AFQ_run will segment the 20 fiber groups defined in the Mori
% white matter atlas and save all the relevant information in the afq
% structure. Aditional groups defined manually or with other segmentation
% algorithms can be added to the afq structure with AFQ_AddNewFiberGroup.
% By default this function will take in (1) an afq strucutre that has already
% been passed through AFQ_run (see AFQ_Create and AFQ_run), (2) the name of
% the new fiber group which should be in each subject's fibers directory,
% and (3) the name of two waypoint ROIs that the fiber group passes through
% which should be in each subjects ROIs directory. The necesary fields in
% the afq structure will be populated, TractProfiles will be calculated and
% added to the structure (See AFQ_CreateTractProfile and
% AFQ_ComputeTractProperties) and the new afq structure will be returned.
% Feel free to take an already segmented fiber group and associate it with
% 2 new ROIs in order to define the edges of the profile differently.
%
% Inputs:
% afq        - An afq structure output from AFQ_run (see also AFQ_Create)
% fgName     - A string containing the name of the fiber group. The fiber
%              group should be in each subject's fibers directory (with the
%              same name). This can be either a .mat file or a .pdb file.
%              If the fgName file does not exist then the fiber group will
%              be defined by intersecting the subject's wholeBrainFG with
%              the two ROIs.
% roi1Name   - A string containing the name of the first waypoint ROI.
%              The ROI should be in each subject's ROIs directory
% roi2Name   - A string containing the name of the second ROI
% cleanFibers- Locigal defining whether the fibers should be cleaned. See
%              AFQ_removeFiberOutliers
% computeVals- Logical defining whether TractProfiles should be calculated
%              for the new fiber group for all of the diffusion (and other)
%              parameters that are  already contained in the afq structure
%
% Copyright Jason D. Yeatman November 2012
%% Argument checking
if ~isafq(afq)
    error('Please enter an afq structure')
end
if ~exist('fgName','var') || isempty(fgName) || ~ischar(fgName)
    error('Please enter the name of the fiber group')
elseif ~(strcmp(fgName(end-3:end),'.mat') || strcmp(fgName(end-3:end),'.pdb'))
    % add file extension
    fgName = [fgName '.mat'];
end
if ~exist('roi1Name','var') || isempty(roi1Name) || ~ischar(roi1Name)
    error('Please enter the name of the first ROI')
elseif ~strcmp(roi1Name(end-3:end),'.mat')
    roi1Name = [roi1Name '.mat'];
end
if ~exist('roi2Name','var') || isempty(roi2Name) || ~ischar(roi2Name)
    error('Please enter the name of the second ROI')
elseif ~strcmp(roi2Name(end-3:end),'.mat')
    roi2Name = [roi2Name '.mat'];
end
if ~exist('cleanFibers','var') || isempty(cleanFibers)
    cleanFibers = true;
end
if ~exist('computeVals','var') || isempty(computeVals)
    computeVals = true;
end
%% Add the new fiber groups and ROIs to the afq structure
afq = AFQ_set(afq,'new fiber group', fgName);
afq = AFQ_set(afq, 'new roi', roi1Name, roi2Name);
% Get the fiber group number. This will be equal to the number of fiber
% groups since it is the last one to be added
fgNumber = AFQ_get(afq,'numfg');
%% Segment the fiber groups if they don't exist
for ii = 1:AFQ_get(afq,'numsubs')
    if ~exist(AFQ_get(afq,[prefix(fgName) 'path'],ii),'file')
        % Load the wholebrain fiber group
        wholebrainFG = AFQ_get(afq,'wholebrain fg', ii);
        % Load the defining ROIs
        [roi1, roi2] = AFQ_LoadROIs(fgNumber,afq.sub_dir{ii}, afq);
        % Intersect the wholebrain fibers with each ROI
        fg_classified = dtiIntersectFibersWithRoi([],'and', 2, roi1, wholebrainFG);
        fg_classified = dtiIntersectFibersWithRoi([],'and', 2, roi2, fg_classified);
        % Set the name
        fg_classified.name = prefix(fgName);
        % Save it
        dtiWriteFiberGroup(fg_classified,AFQ_get(afq,[prefix(fgName) 'path'],ii));
    end
end
%% Clean the fibers if desired
% Loop over subjects
for ii = 1:AFQ_get(afq,'numsubs')
    % Define the current subject to process
    afq = AFQ_set(afq,'current subject',ii);
    % Load the fibers
    if ~exist('fg_classified','var')
        fg_classified = dtiLoadFiberGroup(AFQ_get(afq,[prefix(fgName) 'path'],ii));
    end
    % Only clean if desired
    if cleanFibers == 1
        % only clean if there are enough fibers for it to be worthwhile
        if  length(fg_classified.fibers) > 20
            % clean clipped fiber group if computations are to be done
            % on clipped group
            if afq.params.cleanClippedFibers == 1;
                % load ROIs
                [roi1, roi2] = AFQ_LoadROIs(jj,afq.sub_dirs{ii},afq);
                % clip fiber group
                fg_clip      = dtiClipFiberGroupToROIs(fg_classified,roi1,roi2);
                if length(fg_clip.fibers) > 20
                    % clean clipped fiber group
                    [~, keep] = AFQ_removeFiberOutliers(fg_classified,afq.params.maxDist,afq.params.maxLen,afq.params.numberOfNodes,'mean',0);
                    % remove fibers from unclipped group that do no
                    % survive the clipping
                    fg_classified = fg_classified.fibers(keep);
                end
            else
                % clean un-clipped fiber group
                fg_classified = AFQ_removeFiberOutliers(fg_classified,afq.params.maxDist,afq.params.maxLen,afq.params.numberOfNodes,'mean',0,afq.params.cleanIter);
            end
        end
        % Define the full path to the new cleaned fiber group
        fgpath = fullfile(afq.sub_dirs{ii},'fibers',[prefix(fgName) '_clean_D' num2str(afq.params.maxDist) '_L'  num2str(afq.params.maxLen) '.mat']);
        % Save the fiber group
        dtiWriteFiberGroup(fg_classified, fgpath);
        % And add them to the afq structure
        afq.files.fibers.([prefix(fgName) '_clean']){ii} = fgpath;
    end
    %% Compute tract profiles
    if computeVals == 1
        fprintf('\nComputing Tract Profiles for subject %s',afq.sub_dirs{ii});
        % Load the subject's dt6
        dt = dtiLoadDt6(AFQ_get(afq,'dt6path',ii));
        % Determine how much to weight each fiber's contribution to the
        % measurement at the tract core. Higher values mean steaper falloff
        fWeight = AFQ_get(afq,'fiber weighting');
        % By default Tract Profiles of diffusion properties will always be
        % calculated
        [fa, md, rd, ad, cl, TractProfile] = AFQ_ComputeTractProperties(fg_classified, dt, afq.params.numberOfNodes, afq.params.clip2rois, afq.sub_dirs{ii}, fWeight, afq);
        % Parameterize the shape of each fiber group with calculations of
        % curvature and torsion at each point and add it to the tract
        % profile
        [curv, tors, TractProfile] = AFQ_ParamaterizeTractShape(fg_classified, TractProfile);
        % Calculate the volume of each Tract Profile
        TractProfile = AFQ_TractProfileVolume(TractProfile);
        % Add values to the afq structure
        afq = AFQ_set(afq,'vals','subnum',ii,'fgnum',fgNumber, 'fa',fa, ...
            'md',md,'rd',rd,'ad',ad,'cl',cl,'curvature',curv,'torsion',tors);
        % Add Tract Profiles to the afq structure
        afq = AFQ_set(afq,'tract profile','subnum',ii,'fgnum',fgNumber,TractProfile);
        % If any other images were supplied calculate a Tract Profile for that
        % parameter
        numimages = AFQ_get(afq, 'numimages');
        if numimages > 0;
            for jj = 1:numimages
                % Read the image file
                image = readFileNifti(afq.files.images(jj).path{ii});
                % Compute a Tract Profile for that image
                imagevals = AFQ_ComputeTractProperties(fg_classified, image, afq.params.numberOfNodes, afq.params.clip2rois, sub_dirs{ii}, fWeight);
                % Add values to the afq structure
                afq = AFQ_set(afq,'vals','subnum',ii,'fgnum',fgNumber, afq.files.images(jj).name, imagevals);
                clear imagevals
            end
        end
    else
        fprintf('\nTract Profiles already computed for subject %s',sub_dirs{ii});
    end
end
%% Recompute the norms with the new fiber group
[norms, patient_data, control_data, afq] = AFQ_ComputeNorms(afq);