Description of AFQ_directories
Home > functions > AFQ_directories.m
AFQ_directories
PURPOSE
Returns a path to the AFQ directories
SYNOPSIS
function [AFQbase AFQdata AFQfunc AFQutil AFQdoc AFQgui] = AFQ_directories
DESCRIPTION
 Returns a path to the AFQ directories
   [AFQbase AFQdata AFQfunc AFQutil AFQdoc AFQgui] = AFQ_directories
 Written by Jason D. Yeatman, May 2012
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
AFQ_DefineFgEndpoints THIS FUNCTION IS STILL BEING DEVELOPED
AFQ_Segment_PostArcuate Define the posterior segment of the arcuate from a wholebrain fiber group
AFQ_test Perform unit testing on all the AFQ functions.
SOURCE CODE
function [AFQbase AFQdata AFQfunc AFQutil AFQdoc AFQgui] = AFQ_directories
% Returns a path to the AFQ directories
%
%   [AFQbase AFQdata AFQfunc AFQutil AFQdoc AFQgui] = AFQ_directories
%
% Written by Jason D. Yeatman, May 2012
AFQfunc = fileparts(which('AFQ_run'));
AFQbase = fileparts(AFQfunc);
AFQdata = fullfile(AFQbase,'data');
AFQutil = fullfile(AFQbase,'utilities');
AFQdoc  = fullfile(AFQbase,'doc');
AFQgui  = fullfile(AFQbase,'gui');