Description of AFQ_CreateTractProfile
Home > functions > AFQ_CreateTractProfile.m
AFQ_CreateTractProfile
PURPOSE
Create the AFQ Tract Profile structure
SYNOPSIS
function TractProfile = AFQ_CreateTractProfile(varargin)
DESCRIPTION
 Create the AFQ Tract Profile structure
 TractProfile = AFQ_CreateTractProfile(varargin)
CROSS-REFERENCE INFORMATION
This function calls:
afqVarargin
This function is called by:
AFQ_ComputeTractProperties Compute diffusion properties along the trajectory of the fiber groups.
AFQ_Create Create AFQ structure and set default parameters
AFQ_ParamaterizeTractShape Paramaterize curvature and torsion along a tract profile
AFQ_RenderFibers Render a fiber group and tract profile in 3-D
SOURCE CODE
function TractProfile = AFQ_CreateTractProfile(varargin)
% Create the AFQ Tract Profile structure
%
% TractProfile = AFQ_CreateTractProfile(varargin)
%% Create the afq tract profile structure
TractProfile.name    = 'name';
TractProfile.nfibers = [];
TractProfile.vals    = struct('fa',[],'md',[],'rd',[],'ad',[],'cl',[]);
TractProfile.xform   = struct('acpc2mni',[],'mni2acpc',[],'acpc2dt6',[],'dt62acpc',[]);
TractProfile.coords  = struct('acpc',[],'mni',[],'dt6',[]);
TractProfile.fibercov     = [];
TractProfile.fiberCurvature = [];
TractProfile.fiberTorsion = [];
TractProfile.fiberVolume = [];
%% Set fields
TractProfile = afqVarargin(TractProfile,varargin);
%% Check if the old super fiber structure was passed in
if nargin > 0 && sum(strcmpi('superfiber',varargin)) == 1
    idx = find(strcmpi('superfiber',varargin));
    TractProfile.fibercov = varargin{idx+1}.fibervarcovs{1};
    TractProfile.coords.acpc = varargin{idx+1}.fibers{1};
    TractProfile.nfibers = varargin{idx+1}.n;
end