Description of AFQ_WholebrainTractography
Home > functions > AFQ_WholebrainTractography.m
AFQ_WholebrainTractography
PURPOSE
Perform whole brain deterministic tractography within a white matter mask
SYNOPSIS
function fg = AFQ_WholebrainTractography(dt,run_mode,params)
DESCRIPTION
 Perform whole brain deterministic tractography within a white matter mask
      fg = AFQ_WholebrainTractography(dt, [run_mode], params)
 Inputs:
 dt       = a dt6 structure (generated by dtiInit).
 run_mode = If 'test' then fewer (10K) fibers are tracked for efficient
            debugging. This is achieved by setting a higher fa mask
            threshold and fewer seeds per voxel.  Otherwise don't define.
 params   = A structure of parameters defining the fiber parameters for
            fiber tracking. Can also be an AFQ structure which contains
            these parameters
 Outputs:
 fg       = A wholebrain fiber group.
 Example:
 dt = dtiLoadDt6('subj1/dt6.mat')
 fg = AFQ_WholebrainTractography(dt);
 (c) Jason Yeatman, VISTA Lab, Stanford University, 2011
CROSS-REFERENCE INFORMATION
This function calls:
AFQ_get Get value from afq structure
isafq Check if a variable is an afq structure
This function is called by:
AFQ_SegmentFiberGroups Categorizes each fiber in a group into one of the 20 tracts defined in
AFQ_Segment_PostArcuate Define the posterior segment of the arcuate from a wholebrain fiber group
AFQ_run Run AFQ analysis on a set of subjects to generate Tract Profiles of white
AFQ_example % Example AFQ analysis
SOURCE CODE
function fg = AFQ_WholebrainTractography(dt,run_mode,params)
% Perform whole brain deterministic tractography within a white matter mask
%
%      fg = AFQ_WholebrainTractography(dt, [run_mode], params)
%
% Inputs:
% dt       = a dt6 structure (generated by dtiInit).
% run_mode = If 'test' then fewer (10K) fibers are tracked for efficient
%            debugging. This is achieved by setting a higher fa mask
%            threshold and fewer seeds per voxel.  Otherwise don't define.
% params   = A structure of parameters defining the fiber parameters for
%            fiber tracking. Can also be an AFQ structure which contains
%            these parameters
% Outputs:
% fg       = A wholebrain fiber group.
%
% Example:
%
% dt = dtiLoadDt6('subj1/dt6.mat')
% fg = AFQ_WholebrainTractography(dt);
%
% (c) Jason Yeatman, VISTA Lab, Stanford University, 2011
%% Initialize parameters
if ~exist('params','var') || isempty(params)
    % This defines which voxels will be seeded for tractography.
    if ~exist('run_mode','var') || isempty(run_mode)
        opts.faMaskThresh = 0.30;
    elseif strcmp(run_mode,'test')
        % Set a higher fa threshold, to reduce the number of fibers.
        opts.faMaskThresh = 0.35;
    end
    % Distance between steps in the tractography algoithm
    opts.stepSizeMm = 1;
    % Stopping criteria FA<0.2
    opts.faThresh = 0.2;
    % Discard Fibers shorter than 50mm or longer than 250mm
    opts.lengthThreshMm = [50 250];
    % Stopping criteria angle between steps >30 degrees
    opts.angleThresh = 30;
    % Unknown.....
    opts.wPuncture = 0.2;
    % There are multip.e algorithms that can be used.  We prefer STT. See:
    % Basser PJ, Pajevic S, Pierpaoli C, Duda J, Aldroubi A. 2000.
    % In vivo fiber tractography using DT-MRI data.
    % Magnetic Resonance in Medicine 44(4):625-32.
    opts.whichAlgorithm = 1;
    % Interpolation method. After each step we interpolate the tensor at that
    % point. Trilinear interpolation works well.
    opts.whichInterp = 1;
    % This adds some randomness to each seed point. Each seed point is move
    % randomly by randn*.1mm
    opts.offsetJitter = 0;
    % We seed in voxel in multiple locations. [0.25 and 0.75] Seeds each voxel
    % at 8 equidistant locations.  For one seed in the middle of the voxel use
    % opts.seedVoxelOffsets = 0.5;
    if ~exist('run_mode','var') || isempty(run_mode)
        opts.seedVoxelOffsets = [0.25 0.75];
    elseif strcmp(run_mode,'test')
        opts.seedVoxelOffsets = [0.5];
    end
elseif isafq(params)
    % If an afq structure is passed in get the tracking parameters and also
    % check if tracking should be done based on CSD with mrtrix
    opts = AFQ_get(params,'tracking parameters');
    mrtrix = AFQ_get(params,'use mrtrix');
else
    % Check to make sure the user defined all the propper parameters
    check = isfield(params,'seedVoxelOffsets')&&isfield(params,'whichInterp')&&...
        isfield(params,'faThresh')&&isfield(params,'whichAlgorithm');
    if check == 0
        error('You did not define all the parameters! Try running with dafaults')
    end
end
%% Track with mrtrix if the right files are there
if exist('mrtrix','var') && mrtrix == 1
    mrtrixpaths = AFQ_get(params,'mrtrix paths',params.currentsub);
    [status, results, fg, pathstr] = mrtrix_track(mrtrixpaths.csd, mrtrixpaths.wm, mrtrixpaths.wm, 'stream', 500000,[],[],1);
else
    %% Otherwise track with mrdiffusion
    % Compute FA at every voxel
    fa = dtiComputeFA(dt.dt6);
    % Sometimes noise can cause impossible FA values so we clip them
    fa(fa>1) = 1; fa(fa<0) = 0;
    %% Create an ROI for wholebrain tractography
    roiAll = dtiNewRoi('all');
    % Make a mask of voxels with FA>faMaskThresh
    mask = fa >= opts.faMaskThresh;
    % Convert mask image to a list of coordinates
    [x,y,z] = ind2sub(size(mask), find(mask));
    clear mask fa;
    % Transofrm mask coordinates to subjects ACPC space
    roiAll.coords = mrAnatXformCoords(dt.xformToAcpc, [x,y,z]);
    clear x y z;
    % Smooth the ROI and fill holes
    roiAll = dtiRoiClean(roiAll,3,{'fillHoles'});
    %% Perform wholebrain tractography
    fg = dtiFiberTrack(dt.dt6, roiAll.coords, dt.mmPerVoxel, dt.xformToAcpc, 'wholeBrain', opts);
end
return
%% Comments and debugging