Description of vertex_neighbours
Home > 3Dvis > refinepatch_version2b > vertex_neighbours.m
vertex_neighbours
PURPOSE
This function VERTEX_NEIGHBOURS will search in a face list for all
SYNOPSIS
function Ne=vertex_neighbours(FV)
DESCRIPTION
 This function VERTEX_NEIGHBOURS will search in a face list for all
 the neigbours of each vertex.
 Ne=vertex_neighbours(FV)
CROSS-REFERENCE INFORMATION
This function calls:
vertex_neighbours_double
vertex_neighbours_double
This function is called by:
patchcurvature This function calculates the principal curvature directions and values
refinepatch This function "refinepatch" refines a triangular mesh with
smoothpatch This function PATCHSMOOTH smooths a triangulated Mesh, with accurate
SOURCE CODE
function Ne=vertex_neighbours(FV)
% This function VERTEX_NEIGHBOURS will search in a face list for all
% the neigbours of each vertex.
%
% Ne=vertex_neighbours(FV)
%
Ne=vertex_neighbours_double(FV.faces(:,1),FV.faces(:,2),FV.faces(:,3),FV.vertices(:,1),FV.vertices(:,2),FV.vertices(:,3));