Description of CreateParamsStruct
Home > utilities > CreateParamsStruct.m
CreateParamsStruct
PURPOSE
Create a parameters structure from a cell array.
SYNOPSIS
function params = CreateParamsStruct(c)
DESCRIPTION
 Create a parameters structure from a cell array.
 params = CreateParamsStruct(c)
 Take a cell array and convert it to a structure where each field in the
 structure is named based on the odd numbered cells of the array and the
 values in each field come from the even numbered cells in the array. This
 function is useful for taking 'param', val, pairs from varargin and
 putting them in a structure
CROSS-REFERENCE INFORMATION
This function calls:
isparams Check if a variable is a params structure
This function is called by:
AFQ_RenderCorticalSurface Render the cortical surface from a binary segmentation image
AFQ_RenderRoi Render an ROI as a 3D surface
AFQ_meshColor Color the a mesh based on an overlay image or surface curvature
AFQ_meshCreate Create a mesh structure and build a 3d mesh from a nifti image
SOURCE CODE
function params = CreateParamsStruct(c)
% Create a parameters structure from a cell array.
%
% params = CreateParamsStruct(c)
%
% Take a cell array and convert it to a structure where each field in the
% structure is named based on the odd numbered cells of the array and the
% values in each field come from the even numbered cells in the array. This
% function is useful for taking 'param', val, pairs from varargin and
% putting them in a structure
if ~isparams(c) && iscell(c)
    % If the cell array only contains one cell check if it is a params
    % structure and if so return it
    if length(c) == 1 && isparams(c{1})
        params = c{1};
    elseif length(c) == 1 && ~isparams(c{1})
        params = c;
    else
        params = struct;
        params.type = 'params version 1';
        for ii = 1:2:length(c)
            params.(c{ii}) = c{ii+1};
        end
    end
end