Description of isafq
Home > utilities > isafq.m
isafq
PURPOSE
Check if a variable is an afq structure
SYNOPSIS
function log = isafq(afq)
DESCRIPTION
 Check if a variable is an afq structure
 log = isafq(afq)
 Returns a 0 (false) if the input is not an afq structure and a 1 (true)
 if it is
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
AFQ_AddNewFiberGroup THIS FUNCTION IS STILL BEING DEVELOPED
AFQ_MakeFGProbabilityMap Make a fiber tract probability map from fiber group segmentations
AFQ_WholebrainTractography Perform whole brain deterministic tractography within a white matter mask
AFQ_pca Perform principal components analysis on AFQ Tract Profiles
AFQ_plot This function will plot AFQ results in a variety of ways
SOURCE CODE
function log = isafq(afq)
% Check if a variable is an afq structure
%
% log = isafq(afq)
%
% Returns a 0 (false) if the input is not an afq structure and a 1 (true)
% if it is
if exist('afq','var') && ~isempty(afq)
    log = isstruct(afq) && isfield(afq,'type') && strcmp(afq.type,'afq version 1');
else
    log = false;
end