Description of isparams
Home > utilities > isparams.m
isparams
PURPOSE
Check if a variable is a params structure
SYNOPSIS
function L = isparams(s)
DESCRIPTION
 Check if a variable is a params structure
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
AFQ_meshColor Color the a mesh based on an overlay image or surface curvature
AFQ_meshCreate Create a mesh structure and build a 3d mesh from a nifti image
CreateParamsStruct Create a parameters structure from a cell array.
SOURCE CODE
function L = isparams(s)
% Check if a variable is a params structure
if isstruct(s) && isfield(s,'type') && strcmp('params version 1',s.type)
    L = true;
else
    L = false;
end